[images]
  remote_images = ["https://ysxopfifneumlahkorft.supabase.co/.*"]

[[headers]]
  for = "/.netlify/images*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
